
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Apr  3 2024 23:31:21 +07 (Apr  3 2024 16:31:21 UTC)

// Verification Directory fv/boundFlasher 

module boundFlasher(clk, flick, rst, leds);
  input clk, flick, rst;
  output [15:0] leds;
  wire clk, flick, rst;
  wire [15:0] leds;
  wire [31:0] counter;
  wire [2:0] state;
  wire inc_add_59_40_n_451, inc_add_59_40_n_455, inc_add_59_40_n_458,
       inc_add_59_40_n_460, inc_add_59_40_n_464, inc_add_59_40_n_466,
       inc_add_59_40_n_469, inc_add_59_40_n_471;
  wire inc_add_59_40_n_472, inc_add_59_40_n_477, inc_add_59_40_n_479,
       inc_add_59_40_n_480, inc_add_59_40_n_483, inc_add_59_40_n_485,
       inc_add_59_40_n_487, inc_add_59_40_n_489;
  wire inc_add_59_40_n_491, inc_add_59_40_n_493, inc_add_59_40_n_494,
       inc_add_59_40_n_497, inc_add_59_40_n_500, inc_add_59_40_n_501,
       inc_add_59_40_n_502, inc_add_59_40_n_506;
  wire inc_add_59_40_n_507, inc_add_59_40_n_510, inc_add_59_40_n_511,
       inc_add_59_40_n_515, inc_add_59_40_n_516, inc_add_59_40_n_518,
       inc_add_59_40_n_523, inc_add_59_40_n_529;
  wire inc_add_59_40_n_542, inc_add_59_40_n_548, inc_add_59_40_n_551,
       inc_add_59_40_n_554, inc_add_59_40_n_589, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_12, n_13, n_14, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_41, n_42, n_45, n_47, n_49, n_50, n_52;
  wire n_53, n_54, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_144, n_145;
  wire n_146, n_147, n_149, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_174;
  wire n_175, n_176, n_178, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_199, n_200, n_201, n_202, n_203, n_204, n_217;
  wire n_222, n_223, n_226, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_245, n_246, n_247, n_248, n_249, n_252;
  wire n_253, n_254, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_302, n_304, n_305, n_306, n_308, n_309;
  wire n_310, n_312, n_313, n_314, n_316, n_317, n_318, n_320;
  wire n_321, n_322, n_324, n_325, n_326, n_328, n_329, n_343;
  wire n_344, n_373, n_374, n_375, n_378, n_380, n_381, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_452, n_453;
  wire n_454, n_455, n_456, n_457, n_458, n_459, n_460, n_461;
  wire n_462, n_463, n_464, n_465, n_466, n_467, n_468, n_469;
  wire n_470, n_471, n_475, n_476, n_477, n_478, n_479, n_480;
  wire n_481, n_482, n_483, n_484, n_485, n_486, n_487, n_488;
  wire n_489, n_490, n_491, n_492, n_493;
  DFFRHQX1 \counter_reg[1] (.RN (n_452), .CK (clk), .D (n_276), .Q
       (counter[1]));
  DFFRX1 \counter_reg[2] (.RN (n_452), .CK (clk), .D (n_275), .Q
       (counter[2]), .QN (n_291));
  DFFRHQX1 \counter_reg[3] (.RN (n_452), .CK (clk), .D (n_274), .Q
       (counter[3]));
  DFFRHQX1 \counter_reg[5] (.RN (n_452), .CK (clk), .D (n_272), .Q
       (counter[5]));
  DFFRHQX1 \counter_reg[7] (.RN (n_452), .CK (clk), .D (n_270), .Q
       (counter[7]));
  DFFRHQX1 \counter_reg[9] (.RN (n_452), .CK (clk), .D (n_268), .Q
       (counter[9]));
  DFFRHQX1 \counter_reg[11] (.RN (n_452), .CK (clk), .D (n_266), .Q
       (counter[11]));
  DFFRHQX1 \counter_reg[12] (.RN (n_452), .CK (clk), .D (n_265), .Q
       (counter[12]));
  DFFRHQX1 \counter_reg[14] (.RN (n_452), .CK (clk), .D (n_263), .Q
       (counter[14]));
  DFFRHQX1 \counter_reg[15] (.RN (n_452), .CK (clk), .D (n_262), .Q
       (counter[15]));
  DFFRHQX1 \counter_reg[16] (.RN (n_452), .CK (clk), .D (n_261), .Q
       (counter[16]));
  DFFRHQX1 \counter_reg[19] (.RN (n_452), .CK (clk), .D (n_288), .Q
       (counter[19]));
  DFFRHQX1 \counter_reg[20] (.RN (n_452), .CK (clk), .D (n_287), .Q
       (counter[20]));
  DFFRHQX1 \counter_reg[21] (.RN (n_452), .CK (clk), .D (n_285), .Q
       (counter[21]));
  DFFRHQX1 \counter_reg[23] (.RN (n_452), .CK (clk), .D (n_283), .Q
       (counter[23]));
  DFFRHQX1 \counter_reg[26] (.RN (n_452), .CK (clk), .D (n_280), .Q
       (counter[26]));
  DFFRHQX1 \counter_reg[28] (.RN (n_452), .CK (clk), .D (n_278), .Q
       (counter[28]));
  DFFRHQX1 \counter_reg[29] (.RN (n_452), .CK (clk), .D (n_277), .Q
       (counter[29]));
  DFFHQX4 \leds_reg[0] (.CK (clk), .D (n_243), .Q (leds[0]));
  DFFHQX4 \leds_reg[1] (.CK (clk), .D (n_242), .Q (leds[1]));
  DFFHQX4 \leds_reg[9] (.CK (clk), .D (n_238), .Q (leds[9]));
  DFFRHQX2 \state_reg[0] (.RN (n_452), .CK (clk), .D (n_392), .Q
       (state[0]));
  DFFRX2 \state_reg[2] (.RN (n_452), .CK (clk), .D (n_252), .Q
       (state[2]), .QN (n_4));
  OAI21X4 g12322__2398(.A0 (n_485), .A1 (n_399), .B0 (n_101), .Y
       (n_290));
  OAI21X4 g12323__5107(.A0 (n_484), .A1 (n_399), .B0 (n_93), .Y
       (n_289));
  OAI21X4 g12324__6260(.A0 (n_481), .A1 (n_254), .B0 (n_116), .Y
       (n_288));
  OAI21X4 g12325__4319(.A0 (n_22), .A1 (n_254), .B0 (n_114), .Y
       (n_287));
  OAI21X4 g12326__8428(.A0 (n_27), .A1 (n_399), .B0 (n_120), .Y
       (n_286));
  OAI21X4 g12327__5526(.A0 (n_21), .A1 (n_254), .B0 (n_113), .Y
       (n_285));
  OAI21X4 g12328__6783(.A0 (n_49), .A1 (n_399), .B0 (n_121), .Y
       (n_284));
  OAI21X4 g12329__3680(.A0 (n_482), .A1 (n_254), .B0 (n_111), .Y
       (n_283));
  OAI21X4 g12330__1617(.A0 (n_50), .A1 (n_399), .B0 (n_110), .Y
       (n_282));
  OAI21X4 g12331__2802(.A0 (n_45), .A1 (n_399), .B0 (n_109), .Y
       (n_281));
  OAI21X4 g12332__1705(.A0 (n_38), .A1 (n_254), .B0 (n_108), .Y
       (n_280));
  OAI21X4 g12333__5122(.A0 (n_483), .A1 (n_399), .B0 (n_107), .Y
       (n_279));
  OAI21X4 g12334__8246(.A0 (n_16), .A1 (n_254), .B0 (n_106), .Y
       (n_278));
  OAI21X4 g12335__7098(.A0 (n_23), .A1 (n_254), .B0 (n_117), .Y
       (n_277));
  OAI21X4 g12338__6131(.A0 (n_476), .A1 (n_254), .B0 (n_99), .Y
       (n_276));
  OAI21X4 g12339__1881(.A0 (n_26), .A1 (n_399), .B0 (n_96), .Y (n_275));
  OAI21X4 g12340__5115(.A0 (n_477), .A1 (n_254), .B0 (n_118), .Y
       (n_274));
  OAI21X4 g12341__7482(.A0 (n_13), .A1 (n_399), .B0 (n_97), .Y (n_273));
  OAI21X4 g12342__4733(.A0 (n_14), .A1 (n_254), .B0 (n_95), .Y (n_272));
  OAI21X4 g12343__6161(.A0 (n_25), .A1 (n_399), .B0 (n_115), .Y
       (n_271));
  OAI21X4 g12344__9315(.A0 (n_478), .A1 (n_254), .B0 (n_98), .Y
       (n_270));
  OAI21X4 g12345__9945(.A0 (n_17), .A1 (n_399), .B0 (n_102), .Y
       (n_269));
  OAI21X4 g12346__2883(.A0 (n_41), .A1 (n_254), .B0 (n_105), .Y
       (n_268));
  OAI21X4 g12347__2346(.A0 (n_42), .A1 (n_399), .B0 (n_94), .Y (n_267));
  OAI21X4 g12348__1666(.A0 (n_479), .A1 (n_254), .B0 (n_119), .Y
       (n_266));
  OAI21X4 g12349__7410(.A0 (n_12), .A1 (n_254), .B0 (n_92), .Y (n_265));
  OAI21X4 g12350__6417(.A0 (n_18), .A1 (n_399), .B0 (n_91), .Y (n_264));
  OAI21X4 g12351__5477(.A0 (n_19), .A1 (n_254), .B0 (n_90), .Y (n_263));
  OAI21X4 g12352__2398(.A0 (n_480), .A1 (n_254), .B0 (n_89), .Y
       (n_262));
  OAI21X4 g12353__5107(.A0 (n_47), .A1 (n_254), .B0 (n_88), .Y (n_261));
  OAI21X4 g12354__6260(.A0 (n_20), .A1 (n_399), .B0 (n_112), .Y
       (n_260));
  CLKINVX20 g12361(.A (n_253), .Y (n_254));
  OAI21X1 g12362__3680(.A0 (n_133), .A1 (flick), .B0 (n_249), .Y
       (n_252));
  NAND2X8 g12364__2802(.A (n_61), .B (n_248), .Y (n_253));
  OAI21X1 g12375__5122(.A0 (n_29), .A1 (n_226), .B0 (state[2]), .Y
       (n_249));
  NOR2X4 g12376__8246(.A (n_246), .B (n_241), .Y (n_248));
  NOR2X8 g12388__6131(.A (n_222), .B (flick), .Y (n_241));
  CLKAND2X6 g12392__1881(.A (n_60), .B (n_387), .Y (n_247));
  NOR2X1 g12407__9945(.A (state[0]), .B (n_168), .Y (n_223));
  AND2X1 g12408__2883(.A (n_145), .B (n_169), .Y (n_222));
  NOR2X8 g12414__5477(.A (n_169), .B (flick), .Y (n_217));
  OR2X1 g12423__1617(.A (n_28), .B (n_168), .Y (n_226));
  AOI21X4 g12428__7098(.A0 (leds[13]), .A1 (n_59), .B0 (n_159), .Y
       (n_204));
  OAI211X1 g12429__6131(.A0 (n_28), .A1 (n_139), .B0 (n_84), .C0
       (n_144), .Y (n_203));
  AOI21X4 g12430__1881(.A0 (leds[0]), .A1 (n_59), .B0 (n_0), .Y
       (n_202));
  AOI21X4 g12431__5115(.A0 (leds[1]), .A1 (n_59), .B0 (n_181), .Y
       (n_201));
  AOI21X4 g12432__7482(.A0 (leds[2]), .A1 (n_59), .B0 (n_158), .Y
       (n_200));
  AOI21X4 g12433__4733(.A0 (leds[3]), .A1 (n_59), .B0 (n_178), .Y
       (n_199));
  AOI21X4 g12438__2346(.A0 (leds[8]), .A1 (n_59), .B0 (n_167), .Y
       (n_194));
  AOI21X4 g12439__1666(.A0 (leds[9]), .A1 (n_59), .B0 (n_188), .Y
       (n_193));
  AOI21X4 g12440__7410(.A0 (leds[10]), .A1 (n_59), .B0 (n_189), .Y
       (n_192));
  AOI21X4 g12441__6417(.A0 (leds[11]), .A1 (n_59), .B0 (n_163), .Y
       (n_191));
  AOI21X4 g12442__5477(.A0 (leds[12]), .A1 (n_59), .B0 (n_162), .Y
       (n_190));
  NOR2X4 g12444__2398(.A (n_34), .B (n_344), .Y (n_189));
  NOR2X4 g12445__5107(.A (n_32), .B (n_344), .Y (n_188));
  NOR2X4 g12447__4319(.A (n_34), .B (n_381), .Y (n_186));
  NOR2X4 g12448__8428(.A (n_5), .B (n_381), .Y (n_185));
  NOR2X4 g12449__5526(.A (n_5), .B (n_343), .Y (n_184));
  NOR2X4 g12451__6783(.A (n_32), .B (n_381), .Y (n_183));
  NOR2X4 g12452__3680(.A (n_36), .B (n_381), .Y (n_182));
  NOR2X4 g12453__1617(.A (n_33), .B (n_344), .Y (n_181));
  NOR2X4 g12454__2802(.A (n_37), .B (n_381), .Y (n_180));
  NOR2X4 g12456__5122(.A (n_37), .B (n_343), .Y (n_178));
  NOR2X4 g12458__7098(.A (n_6), .B (n_381), .Y (n_176));
  NOR2X4 g12459__6131(.A (n_30), .B (n_343), .Y (n_175));
  NOR2X4 g12460__1881(.A (n_31), .B (n_381), .Y (n_174));
  NOR2X4 g12463__4733(.A (n_31), .B (n_343), .Y (n_171));
  NOR2X4 g12464__6161(.A (n_35), .B (n_344), .Y (n_167));
  NOR2X8 g12465__9315(.A (n_145), .B (flick), .Y (n_166));
  NOR2X4 g12466__9945(.A (n_9), .B (n_381), .Y (n_165));
  NOR2X4 g12467__2883(.A (n_30), .B (n_381), .Y (n_164));
  NOR2X4 g12468__2346(.A (n_9), .B (n_344), .Y (n_163));
  NOR2X4 g12469__1666(.A (n_7), .B (n_343), .Y (n_162));
  NOR2X4 g12470__7410(.A (n_33), .B (n_381), .Y (n_161));
  NOR2X4 g12471__6417(.A (n_8), .B (n_381), .Y (n_160));
  NOR2X4 g12472__5477(.A (n_10), .B (n_344), .Y (n_159));
  NOR2X4 g12474__2398(.A (n_36), .B (n_344), .Y (n_158));
  NOR2X4 g12475__5107(.A (n_35), .B (n_381), .Y (n_157));
  NOR2X4 g12476__6260(.A (n_10), .B (n_381), .Y (n_156));
  NOR2X4 g12477__4319(.A (n_7), .B (n_381), .Y (n_155));
  NOR2X4 g12478__8428(.A (n_6), .B (n_343), .Y (n_154));
  OAI22X2 g12479__5526(.A0 (n_131), .A1 (n_52), .B0 (n_29), .B1
       (n_136), .Y (n_153));
  AND3X4 g12480__6783(.A (n_131), .B (n_57), .C (n_58), .Y (n_170));
  OAI22X4 g12481__3680(.A0 (n_132), .A1 (flick), .B0 (state[2]), .B1
       (n_66), .Y (n_152));
  OR3X1 g12482__1617(.A (n_130), .B (n_29), .C (n_135), .Y (n_169));
  OAI21X2 g12483__2802(.A0 (n_84), .A1 (n_128), .B0 (n_144), .Y
       (n_168));
  CLKINVX16 g12487(.A (n_149), .Y (n_59));
  CLKINVX12 g12488(.A (n_146), .Y (n_149));
  AND2X1 g12490__5122(.A (state[0]), .B (n_139), .Y (n_147));
  NOR2X8 g12492__7098(.A (n_137), .B (rst), .Y (n_146));
  CLKINVX12 g12495(.A (n_140), .Y (n_142));
  OAI2BB1X1 g12496__6131(.A0N (n_130), .A1N (state[2]), .B0 (n_131), .Y
       (n_141));
  OR3X4 g12497__1881(.A (n_129), .B (n_4), .C (n_135), .Y (n_145));
  OAI2BB1X1 g12498__5115(.A0N (n_124), .A1N (n_127), .B0 (n_85), .Y
       (n_144));
  NOR2X8 g12499__7482(.A (n_1), .B (rst), .Y (n_140));
  NAND2X1 g12500__4733(.A (n_85), .B (n_128), .Y (n_138));
  OR2X1 g12501__6161(.A (n_28), .B (n_56), .Y (n_137));
  NOR2X1 g12502__9315(.A (n_130), .B (state[2]), .Y (n_136));
  NAND2BX1 g12503__9945(.AN (n_52), .B (n_131), .Y (n_139));
  OR4X1 g12506__2346(.A (n_57), .B (state[2]), .C (n_68), .D (n_28), .Y
       (n_133));
  NAND2X1 g12507__1666(.A (n_129), .B (n_29), .Y (n_132));
  OR2X1 g12509__7410(.A (n_28), .B (n_128), .Y (n_135));
  OR4X1 g12511__6417(.A (leds[7]), .B (n_65), .C (n_104), .D (n_122),
       .Y (n_131));
  NOR2X2 g12512__5477(.A (n_100), .B (n_126), .Y (n_130));
  OAI32X1 g12514__2398(.A0 (leds[4]), .A1 (n_73), .A2 (n_29), .B0
       (n_104), .B1 (n_475), .Y (n_127));
  NOR2X1 g12515__5107(.A (n_86), .B (n_126), .Y (n_129));
  NOR2X2 g12516__6260(.A (n_125), .B (n_123), .Y (n_128));
  OR3X1 g12517__4319(.A (n_72), .B (n_81), .C (n_87), .Y (n_125));
  OR4X1 g12518__8428(.A (n_30), .B (n_5), .C (n_6), .D (n_104), .Y
       (n_126));
  NOR4X1 g12519__5526(.A (leds[7]), .B (leds[5]), .C (leds[6]), .D
       (n_122), .Y (n_124));
  OR4X1 g12520__6783(.A (n_75), .B (n_71), .C (n_74), .D (n_76), .Y
       (n_123));
  NAND2X1 g12521__3680(.A (counter[22]), .B (n_82), .Y (n_121));
  NAND2X1 g12522__1617(.A (counter[18]), .B (n_82), .Y (n_120));
  NAND2X1 g12523__2802(.A (counter[11]), .B (n_83), .Y (n_119));
  NAND2X1 g12524__1705(.A (counter[3]), .B (n_83), .Y (n_118));
  NAND2X1 g12525__5122(.A (counter[29]), .B (n_83), .Y (n_117));
  NAND2X1 g12526__8246(.A (counter[19]), .B (n_83), .Y (n_116));
  NAND2X1 g12527__7098(.A (counter[6]), .B (n_82), .Y (n_115));
  NAND2X1 g12528__6131(.A (counter[20]), .B (n_2), .Y (n_114));
  NAND2X1 g12529__1881(.A (counter[21]), .B (n_83), .Y (n_113));
  NAND2X1 g12530__5115(.A (counter[17]), .B (n_82), .Y (n_112));
  NAND2X1 g12531__7482(.A (counter[23]), .B (n_83), .Y (n_111));
  NAND2X1 g12532__4733(.A (counter[24]), .B (n_82), .Y (n_110));
  NAND2X1 g12533__6161(.A (counter[25]), .B (n_82), .Y (n_109));
  NAND2X1 g12534__9315(.A (counter[26]), .B (n_83), .Y (n_108));
  NAND2X1 g12535__9945(.A (counter[27]), .B (n_82), .Y (n_107));
  NAND2X1 g12536__2883(.A (counter[28]), .B (n_83), .Y (n_106));
  NAND2X1 g12537__2346(.A (counter[9]), .B (n_83), .Y (n_105));
  NAND2X1 g12538__1666(.A (n_70), .B (n_77), .Y (n_122));
  NAND2X1 g12539__7410(.A (counter[8]), .B (n_82), .Y (n_102));
  NAND2X1 g12540__6417(.A (counter[31]), .B (n_83), .Y (n_101));
  OR4X1 g12541__5477(.A (leds[15]), .B (n_31), .C (n_69), .D (n_53), .Y
       (n_100));
  NAND2X1 g12542__2398(.A (counter[1]), .B (n_82), .Y (n_99));
  NAND2X1 g12543__5107(.A (counter[7]), .B (n_2), .Y (n_98));
  NAND2X1 g12544__6260(.A (counter[4]), .B (n_3), .Y (n_97));
  NAND2X1 g12545__4319(.A (counter[2]), .B (n_82), .Y (n_96));
  NAND2X1 g12546__8428(.A (counter[5]), .B (n_83), .Y (n_95));
  NAND2X1 g12547__5526(.A (counter[10]), .B (n_82), .Y (n_94));
  NAND2X1 g12548__6783(.A (counter[30]), .B (n_3), .Y (n_93));
  NAND2X1 g12549__3680(.A (counter[12]), .B (n_83), .Y (n_92));
  NAND2X1 g12550__1617(.A (counter[13]), .B (n_82), .Y (n_91));
  NAND2X1 g12551__2802(.A (counter[14]), .B (n_83), .Y (n_90));
  NAND2X1 g12552__1705(.A (counter[15]), .B (n_83), .Y (n_89));
  NAND2X1 g12553__5122(.A (counter[16]), .B (n_82), .Y (n_88));
  NAND2X1 g12554__8246(.A (n_78), .B (n_79), .Y (n_87));
  OR4X1 g12555__7098(.A (n_8), .B (n_31), .C (n_69), .D (n_80), .Y
       (n_86));
  OR4X1 g12556__6131(.A (n_33), .B (n_37), .C (n_36), .D (n_67), .Y
       (n_104));
  CLKINVX4 g12559(.A (n_54), .Y (n_83));
  CLKINVX4 g12560(.A (n_54), .Y (n_82));
  OR4X1 g12563__5115(.A (counter[28]), .B (counter[27]), .C
       (counter[26]), .D (counter[25]), .Y (n_81));
  OR4X1 g12564__7482(.A (n_10), .B (n_7), .C (n_9), .D (n_34), .Y
       (n_80));
  NOR3X1 g12565__4733(.A (counter[7]), .B (counter[24]), .C (n_64), .Y
       (n_79));
  NOR4X1 g12566__6161(.A (counter[1]), .B (counter[3]), .C
       (counter[4]), .D (n_291), .Y (n_78));
  NOR2X1 g12567__9315(.A (state[0]), .B (n_68), .Y (n_85));
  OR3X1 g12568__9945(.A (n_29), .B (n_4), .C (n_28), .Y (n_84));
  NAND2X1 g12569__2883(.A (n_68), .B (n_28), .Y (n_54));
  OR4X1 g12571__2346(.A (counter[23]), .B (counter[22]), .C
       (counter[21]), .D (counter[20]), .Y (n_76));
  OR4X1 g12572__1666(.A (counter[11]), .B (counter[10]), .C
       (counter[9]), .D (counter[8]), .Y (n_75));
  OR4X1 g12573__7410(.A (counter[19]), .B (counter[18]), .C
       (counter[17]), .D (counter[16]), .Y (n_74));
  OR4X1 g12574__6417(.A (leds[1]), .B (leds[0]), .C (leds[2]), .D
       (leds[3]), .Y (n_73));
  OR4X1 g12575__5477(.A (counter[0]), .B (counter[31]), .C
       (counter[30]), .D (counter[29]), .Y (n_72));
  OR4X1 g12576__2398(.A (counter[15]), .B (counter[14]), .C
       (counter[13]), .D (counter[12]), .Y (n_71));
  AND4X1 g12577__5107(.A (n_31), .B (n_32), .C (n_8), .D (n_35), .Y
       (n_70));
  AND4X1 g12578__6260(.A (n_34), .B (n_7), .C (n_10), .D (n_9), .Y
       (n_77));
  NAND2X1 g12580__4319(.A (leds[1]), .B (leds[0]), .Y (n_67));
  NAND2X1 g12581__8428(.A (leds[10]), .B (leds[9]), .Y (n_69));
  AND2X1 g12582__5526(.A (n_29), .B (n_4), .Y (n_68));
  NOR2X2 g12583__6783(.A (n_29), .B (flick), .Y (n_66));
  NAND2X1 g12584__3680(.A (leds[5]), .B (n_30), .Y (n_65));
  NAND2X1 g12585__1617(.A (counter[5]), .B (counter[6]), .Y (n_64));
  SDFFRHQX1 \counter_reg[0] (.RN (n_452), .CK (clk), .D (n_253), .SI
       (n_82), .SE (counter[0]), .Q (counter[0]));
  DFFRHQX1 \counter_reg[25] (.RN (n_452), .CK (clk), .D (n_281), .Q
       (counter[25]));
  DFFRHQX1 \counter_reg[27] (.RN (n_452), .CK (clk), .D (n_279), .Q
       (counter[27]));
  DFFRHQX1 \counter_reg[30] (.RN (n_452), .CK (clk), .D (n_289), .Q
       (counter[30]));
  DFFRHQX1 \counter_reg[31] (.RN (n_452), .CK (clk), .D (n_290), .Q
       (counter[31]));
  BUFX2 drc_bufs12678(.A (n_82), .Y (n_3));
  BUFX2 drc_bufs12684(.A (n_83), .Y (n_2));
  NOR2BX2 g2__2802(.AN (n_54), .B (n_128), .Y (n_1));
  NOR2BX4 g12738__1705(.AN (leds[1]), .B (n_343), .Y (n_0));
  INVX2 g12740(.A (leds[6]), .Y (n_30));
  INVX2 g12742(.A (leds[2]), .Y (n_33));
  INVX2 g12744(.A (leds[4]), .Y (n_37));
  INVX2 g12746(.A (leds[3]), .Y (n_36));
  INVX2 g12748(.A (leds[8]), .Y (n_31));
  INVX2 g12750(.A (leds[10]), .Y (n_32));
  INVX1 g12752(.A (leds[15]), .Y (n_8));
  INVX2 g12754(.A (leds[9]), .Y (n_35));
  INVX2 g12756(.A (leds[11]), .Y (n_34));
  INVX2 g12758(.A (leds[13]), .Y (n_7));
  INVX2 g12760(.A (leds[14]), .Y (n_10));
  INVX2 g12762(.A (leds[12]), .Y (n_9));
  INVX2 g12764(.A (leds[5]), .Y (n_5));
  INVX2 g12766(.A (leds[7]), .Y (n_6));
  INVX1 g12768(.A (state[0]), .Y (n_28));
  INVX2 g12770(.A (n_475), .Y (n_29));
  INVX1 g12774(.A (n_302), .Y (n_26));
  INVX1 g12778(.A (n_304), .Y (n_13));
  INVX1 g12780(.A (n_305), .Y (n_14));
  INVX1 g12782(.A (n_306), .Y (n_25));
  INVX1 g12786(.A (n_308), .Y (n_17));
  INVX1 g12788(.A (n_309), .Y (n_41));
  INVX1 g12790(.A (n_310), .Y (n_42));
  INVX1 g12794(.A (n_312), .Y (n_12));
  INVX1 g12796(.A (n_313), .Y (n_18));
  INVX1 g12798(.A (n_314), .Y (n_19));
  INVX1 g12802(.A (n_316), .Y (n_47));
  INVX1 g12804(.A (n_317), .Y (n_20));
  INVX1 g12806(.A (n_318), .Y (n_27));
  INVX1 g12810(.A (n_320), .Y (n_22));
  INVX1 g12812(.A (n_321), .Y (n_21));
  INVX1 g12814(.A (n_322), .Y (n_49));
  INVX1 g12818(.A (n_324), .Y (n_50));
  INVX1 g12820(.A (n_325), .Y (n_45));
  INVX1 g12822(.A (n_326), .Y (n_38));
  INVX1 g12826(.A (n_328), .Y (n_16));
  INVX1 g12828(.A (n_329), .Y (n_23));
  AOI21X2 g12850__8246(.A0 (leds[0]), .A1 (n_142), .B0 (n_59), .Y
       (n_62));
  INVX1 g12852(.A (n_130), .Y (n_57));
  INVX1 g12854(.A (n_128), .Y (n_56));
  INVX1 g12856(.A (n_135), .Y (n_58));
  NAND2X2 g12858__7098(.A (n_141), .B (flick), .Y (n_60));
  INVX1 g12860(.A (n_77), .Y (n_53));
  INVX1 g12862(.A (n_68), .Y (n_52));
  ADDHX1 inc_add_59_40_g907__5115(.A (counter[26]), .B
       (inc_add_59_40_n_464), .CO (inc_add_59_40_n_451), .S (n_326));
  ADDHX1 inc_add_59_40_g910__6161(.A (counter[22]), .B
       (inc_add_59_40_n_469), .CO (inc_add_59_40_n_455), .S (n_322));
  ADDHX1 inc_add_59_40_g912__9945(.A (counter[29]), .B
       (inc_add_59_40_n_480), .CO (inc_add_59_40_n_458), .S (n_329));
  ADDHX1 inc_add_59_40_g913__2883(.A (counter[18]), .B
       (inc_add_59_40_n_477), .CO (inc_add_59_40_n_460), .S (n_318));
  ADDHX1 inc_add_59_40_g916__7410(.A (counter[25]), .B
       (inc_add_59_40_n_483), .CO (inc_add_59_40_n_464), .S (n_325));
  ADDHX1 inc_add_59_40_g917__6417(.A (counter[14]), .B
       (inc_add_59_40_n_485), .CO (inc_add_59_40_n_466), .S (n_314));
  ADDHX1 inc_add_59_40_g919__2398(.A (counter[21]), .B
       (inc_add_59_40_n_489), .CO (inc_add_59_40_n_469), .S (n_321));
  ADDHX1 inc_add_59_40_g920__5107(.A (counter[10]), .B
       (inc_add_59_40_n_487), .CO (inc_add_59_40_n_471), .S (n_310));
  NAND3X1 inc_add_59_40_g921__6260(.A (counter[29]), .B (counter[30]),
       .C (inc_add_59_40_n_480), .Y (inc_add_59_40_n_472));
  ADDHX1 inc_add_59_40_g922__4319(.A (counter[17]), .B
       (inc_add_59_40_n_493), .CO (inc_add_59_40_n_477), .S (n_317));
  ADDHX1 inc_add_59_40_g923__8428(.A (counter[6]), .B
       (inc_add_59_40_n_491), .CO (inc_add_59_40_n_479), .S (n_306));
  ADDHX1 inc_add_59_40_g924__5526(.A (counter[28]), .B
       (inc_add_59_40_n_494), .CO (inc_add_59_40_n_480), .S (n_328));
  ADDHX1 inc_add_59_40_g925__6783(.A (counter[24]), .B
       (inc_add_59_40_n_589), .CO (inc_add_59_40_n_483), .S (n_324));
  ADDHX1 inc_add_59_40_g926__3680(.A (counter[13]), .B
       (inc_add_59_40_n_497), .CO (inc_add_59_40_n_485), .S (n_313));
  ADDHX1 inc_add_59_40_g927__1617(.A (counter[9]), .B
       (inc_add_59_40_n_500), .CO (inc_add_59_40_n_487), .S (n_309));
  ADDHX1 inc_add_59_40_g928__2802(.A (counter[20]), .B
       (inc_add_59_40_n_501), .CO (inc_add_59_40_n_489), .S (n_320));
  ADDHX1 inc_add_59_40_g929__1705(.A (counter[5]), .B
       (inc_add_59_40_n_506), .CO (inc_add_59_40_n_491), .S (n_305));
  ADDHX1 inc_add_59_40_g930__5122(.A (counter[16]), .B
       (inc_add_59_40_n_507), .CO (inc_add_59_40_n_493), .S (n_316));
  NOR2BX1 inc_add_59_40_g931__8246(.AN (inc_add_59_40_n_589), .B
       (inc_add_59_40_n_518), .Y (inc_add_59_40_n_494));
  ADDHX1 inc_add_59_40_g932__7098(.A (counter[12]), .B
       (inc_add_59_40_n_511), .CO (inc_add_59_40_n_497), .S (n_312));
  ADDHX1 inc_add_59_40_g934__6131(.A (counter[8]), .B (n_492), .CO
       (inc_add_59_40_n_500), .S (n_308));
  NAND2X2 inc_add_59_40_g936__1881(.A (inc_add_59_40_n_523), .B
       (inc_add_59_40_n_507), .Y (inc_add_59_40_n_502));
  ADDHX1 inc_add_59_40_g938__7482(.A (counter[4]), .B
       (inc_add_59_40_n_515), .CO (inc_add_59_40_n_506), .S (n_304));
  AND2X2 inc_add_59_40_g939__4733(.A (inc_add_59_40_n_529), .B
       (inc_add_59_40_n_511), .Y (inc_add_59_40_n_507));
  ADDHX1 inc_add_59_40_g940__6161(.A (counter[2]), .B
       (inc_add_59_40_n_516), .CO (inc_add_59_40_n_510), .S (n_302));
  AND2X1 inc_add_59_40_g941__9315(.A (n_493), .B (n_492), .Y
       (inc_add_59_40_n_511));
  NOR2X2 inc_add_59_40_g943__2883(.A (inc_add_59_40_n_542), .B
       (inc_add_59_40_n_554), .Y (inc_add_59_40_n_515));
  NAND4XL inc_add_59_40_g945__2346(.A (counter[26]), .B (counter[27]),
       .C (counter[24]), .D (counter[25]), .Y (inc_add_59_40_n_518));
  AND4X1 inc_add_59_40_g946__1666(.A (counter[16]), .B (counter[17]),
       .C (counter[18]), .D (counter[19]), .Y (inc_add_59_40_n_523));
  AND4X1 inc_add_59_40_g948__7410(.A (counter[12]), .B (counter[13]),
       .C (counter[14]), .D (counter[15]), .Y (inc_add_59_40_n_529));
  NAND2X1 inc_add_59_40_g955__4319(.A (counter[22]), .B (counter[23]),
       .Y (inc_add_59_40_n_548));
  NOR4BBX4 inc_add_59_40_g2__8428(.AN (counter[20]), .BN (counter[21]),
       .C (inc_add_59_40_n_548), .D (inc_add_59_40_n_502), .Y
       (inc_add_59_40_n_589));
  NAND2X1 inc_add_59_40_g963__6783(.A (counter[4]), .B (counter[5]), .Y
       (inc_add_59_40_n_551));
  NAND2X2 inc_add_59_40_g965__3680(.A (counter[0]), .B (counter[1]), .Y
       (inc_add_59_40_n_554));
  INVX1 inc_add_59_40_g967(.A (inc_add_59_40_n_502), .Y
       (inc_add_59_40_n_501));
  INVX1 inc_add_59_40_g971(.A (inc_add_59_40_n_554), .Y
       (inc_add_59_40_n_516));
  NAND2X4 g12878__2802(.A (n_487), .B (n_465), .Y (n_231));
  NAND2X4 g12880__1705(.A (n_488), .B (n_464), .Y (n_230));
  NAND2X4 g12882__5122(.A (n_489), .B (n_470), .Y (n_229));
  NAND2X4 g12884__8246(.A (n_490), .B (n_462), .Y (n_239));
  NAND2X4 g12886__7098(.A (n_199), .B (n_466), .Y (n_237));
  NAND2X4 g12888__6131(.A (n_200), .B (n_458), .Y (n_240));
  NAND2X4 g12890__1881(.A (n_193), .B (n_457), .Y (n_232));
  NAND2X4 g12892__5115(.A (n_192), .B (n_459), .Y (n_236));
  NAND2X4 g12894__7482(.A (n_191), .B (n_469), .Y (n_235));
  NAND2X4 g12896__4733(.A (n_190), .B (n_468), .Y (n_234));
  NAND2X4 g12898__6161(.A (n_194), .B (n_461), .Y (n_238));
  NAND2X4 g12900__9315(.A (n_201), .B (n_471), .Y (n_245));
  NAND2X4 g12902__9945(.A (n_204), .B (n_467), .Y (n_233));
  CLKINVX12 g12904(.A (n_142), .Y (n_343));
  CLKINVX12 g12493_0(.A (n_142), .Y (n_344));
  NAND2X4 g12912__2883(.A (n_202), .B (n_460), .Y (n_242));
  DFFHQX1 \leds_reg[15] (.CK (clk), .D (n_486), .Q (leds[15]));
  DFFRHQX1 \counter_reg[4] (.RN (n_452), .CK (clk), .D (n_273), .Q
       (counter[4]));
  DFFHQX1 \leds_reg[12] (.CK (clk), .D (n_235), .Q (leds[12]));
  DFFHQX1 \leds_reg[2] (.CK (clk), .D (n_245), .Q (leds[2]));
  DFFHQX1 \leds_reg[5] (.CK (clk), .D (n_231), .Q (leds[5]));
  DFFHQX1 \leds_reg[8] (.CK (clk), .D (n_239), .Q (leds[8]));
  DFFHQX1 \leds_reg[10] (.CK (clk), .D (n_232), .Q (leds[10]));
  DFFHQX1 \leds_reg[7] (.CK (clk), .D (n_229), .Q (leds[7]));
  DFFHQX1 \leds_reg[3] (.CK (clk), .D (n_240), .Q (leds[3]));
  DFFHQX1 \leds_reg[13] (.CK (clk), .D (n_234), .Q (leds[13]));
  DFFHQX1 \leds_reg[6] (.CK (clk), .D (n_230), .Q (leds[6]));
  DFFHQX1 \leds_reg[11] (.CK (clk), .D (n_236), .Q (leds[11]));
  DFFHQX1 \leds_reg[4] (.CK (clk), .D (n_237), .Q (leds[4]));
  DFFHQX1 \leds_reg[14] (.CK (clk), .D (n_233), .Q (leds[14]));
  AND2X2 g12393__12948(.A (n_56), .B (n_203), .Y (n_246));
  NOR2X8 g39(.A (n_373), .B (n_374), .Y (n_375));
  CLKINVX20 g41(.A (flick), .Y (n_374));
  NOR3BX2 g25(.AN (leds[1]), .B (n_138), .C (rst), .Y (n_378));
  CLKINVX20 g26(.A (n_380), .Y (n_381));
  NOR2X8 g27(.A (n_138), .B (rst), .Y (n_380));
  NOR2X8 g29(.A (n_153), .B (n_386), .Y (n_387));
  NOR2X8 g30(.A (n_385), .B (flick), .Y (n_386));
  NAND2X1 g31(.A (state[2]), .B (n_129), .Y (n_385));
  NAND2X2 g73(.A (n_390), .B (n_391), .Y (n_392));
  AOI21X1 g74(.A0 (state[0]), .A1 (n_168), .B0 (n_389), .Y (n_390));
  NOR2BX4 g75(.AN (n_223), .B (n_388), .Y (n_389));
  NOR2X4 g77(.A (n_52), .B (flick), .Y (n_388));
  NAND2X4 g76(.A (state[0]), .B (n_247), .Y (n_391));
  NAND2X4 g12950(.A (n_393), .B (n_394), .Y (n_395));
  NAND2X4 g12951(.A (n_475), .B (n_247), .Y (n_393));
  AOI22X4 g72(.A0 (n_475), .A1 (n_226), .B0 (n_147), .B1 (n_152), .Y
       (n_394));
  CLKINVX20 g23(.A (n_398), .Y (n_399));
  NAND2X8 g12952(.A (n_396), .B (n_397), .Y (n_398));
  NOR2X6 g12953(.A (n_246), .B (n_217), .Y (n_396));
  NOR2X6 g12954(.A (n_166), .B (n_375), .Y (n_397));
  NAND2X6 g12848__12958(.A (n_170), .B (flick), .Y (n_61));
  CLKINVX4 g13005(.A (rst), .Y (n_452));
  NOR2X2 g13006(.A (n_378), .B (n_454), .Y (n_455));
  CLKAND2X6 g12557__13007(.A (n_453), .B (n_452), .Y (n_454));
  INVX1 g13008(.A (n_84), .Y (n_453));
  AOI21X4 g12427__13009(.A0 (leds[14]), .A1 (n_59), .B0 (n_454), .Y
       (n_456));
  NOR2X4 g12406__13010(.A (n_454), .B (n_186), .Y (n_457));
  NOR2X4 g12416__13011(.A (n_454), .B (n_180), .Y (n_458));
  NOR2X4 g12412__13012(.A (n_454), .B (n_165), .Y (n_459));
  NOR2X4 g12405__13013(.A (n_454), .B (n_161), .Y (n_460));
  NOR2X4 g12422__13014(.A (n_454), .B (n_183), .Y (n_461));
  NOR2X4 g12421__13015(.A (n_454), .B (n_157), .Y (n_462));
  NOR2X4 g12419__13016(.A (n_463), .B (n_176), .Y (n_464));
  CLKAND2X8 g12557__1881_dup(.A (n_453), .B (n_452), .Y (n_463));
  NOR2X4 g12418__13017(.A (n_463), .B (n_164), .Y (n_465));
  NOR2X4 g12417__13018(.A (n_463), .B (n_185), .Y (n_466));
  NOR2X4 g12426__13019(.A (n_463), .B (n_160), .Y (n_467));
  NOR2X4 g12425__13020(.A (n_463), .B (n_156), .Y (n_468));
  NOR2X4 g12424__13021(.A (n_463), .B (n_155), .Y (n_469));
  NOR2X4 g12420__13022(.A (n_463), .B (n_174), .Y (n_470));
  NOR2X4 g12415__13023(.A (n_463), .B (n_182), .Y (n_471));
  DFFRHQX1 \state_reg[1] (.RN (n_452), .CK (clk), .D (n_395), .Q
       (n_475));
  XNOR2X2 g13035(.A (counter[3]), .B (inc_add_59_40_n_510), .Y (n_477));
  XNOR2X2 g13037(.A (counter[11]), .B (inc_add_59_40_n_471), .Y
       (n_479));
  CLKXOR2X2 g13043(.A (counter[31]), .B (inc_add_59_40_n_472), .Y
       (n_485));
  OAI2BB1X2 g13044(.A0N (leds[15]), .A1N (n_142), .B0 (n_456), .Y
       (n_486));
  AOI2BB1X4 g13045(.A0N (n_37), .A1N (n_149), .B0 (n_184), .Y (n_487));
  AOI2BB1X4 g13046(.A0N (n_5), .A1N (n_149), .B0 (n_175), .Y (n_488));
  AOI2BB1X4 g13047(.A0N (n_30), .A1N (n_149), .B0 (n_154), .Y (n_489));
  AOI2BB1X4 g13048(.A0N (n_6), .A1N (n_149), .B0 (n_171), .Y (n_490));
  INVXL g3(.A (n_491), .Y (n_492));
  NAND4BX2 g13049(.AN (inc_add_59_40_n_551), .B (counter[6]), .C
       (counter[7]), .D (inc_add_59_40_n_515), .Y (n_491));
  AND4XL g13050(.A (counter[10]), .B (counter[11]), .C (counter[8]), .D
       (counter[9]), .Y (n_493));
  DFFRHQX1 \counter_reg[24] (.RN (n_452), .CK (clk), .D (n_282), .Q
       (counter[24]));
  DFFRHQX1 \counter_reg[6] (.RN (n_452), .CK (clk), .D (n_271), .Q
       (counter[6]));
  DFFRHQX1 \counter_reg[10] (.RN (n_452), .CK (clk), .D (n_267), .Q
       (counter[10]));
  DFFRHQX1 \counter_reg[8] (.RN (n_452), .CK (clk), .D (n_269), .Q
       (counter[8]));
  DFFRHQX1 \counter_reg[13] (.RN (n_452), .CK (clk), .D (n_264), .Q
       (counter[13]));
  DFFRHQX1 \counter_reg[18] (.RN (n_452), .CK (clk), .D (n_286), .Q
       (counter[18]));
  DFFRHQX1 \counter_reg[17] (.RN (n_452), .CK (clk), .D (n_260), .Q
       (counter[17]));
  DFFRHQX1 \counter_reg[22] (.RN (n_452), .CK (clk), .D (n_284), .Q
       (counter[22]));
  XNOR2X1 g13074(.A (counter[19]), .B (inc_add_59_40_n_460), .Y
       (n_481));
  XNOR2X1 g13080(.A (counter[1]), .B (counter[0]), .Y (n_476));
  NAND2X2 inc_add_59_40_g953__13082(.A (counter[2]), .B (counter[3]),
       .Y (inc_add_59_40_n_542));
  INVX2 g13084(.A (n_170), .Y (n_373));
  XNOR2X1 g13086(.A (counter[15]), .B (inc_add_59_40_n_466), .Y
       (n_480));
  XNOR2X1 g13088(.A (counter[23]), .B (inc_add_59_40_n_455), .Y
       (n_482));
  NAND2X2 g12942__13090(.A (n_62), .B (n_455), .Y (n_243));
  XNOR2X1 g13092(.A (counter[27]), .B (inc_add_59_40_n_451), .Y
       (n_483));
  XNOR2X1 g13094(.A (counter[30]), .B (inc_add_59_40_n_458), .Y
       (n_484));
  XNOR2X1 g13096(.A (counter[7]), .B (inc_add_59_40_n_479), .Y (n_478));
endmodule

